[build]
  publish = "out"
  command = "npm run deploy:build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=()"
    Content-Security-Policy = '''
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://code.jquery.com https://unpkg.com https://www.googletagmanager.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      img-src 'self' data: https:;
      connect-src 'self' https://api.github.com https://www.google-analytics.com;
      media-src 'self';
      object-src 'none';
      base-uri 'self';
      form-action 'self';
      frame-ancestors 'none';
      upgrade-insecure-requests;
    '''

# Cache static assets
[[headers]]
  for = "/assets/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Service Worker - no cache
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# PWA Manifest
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Content-Type = "application/manifest+json"

# API endpoints
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# HTML files
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Redirects for SPA routing
[[redirects]]
  from = "/public/v2.0/*"
  to = "/public/v2.0/index.html"
  status = 200
  conditions = {Role = ["admin"]}

[[redirects]]
  from = "/Games/*"
  to = "/public/Games/:splat"
  status = 301

# Redirect old paths
[[redirects]]
  from = "/v2.0/*"
  to = "/public/v2.0/:splat"
  status = 301

[[redirects]]
  from = "/v1.0/*"
  to = "/public/v1.0/:splat"
  status = 301

# Default redirect to latest version
[[redirects]]
  from = "/"
  to = "/public/v2.0/"
  status = 302
  conditions = {Cookie = ["redirect=auto"]}

# Edge functions for performance
[[edge_functions]]
  function = "image-optimization"
  path = "/assets/images/*"

# Build plugins
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
  [plugins.inputs.thresholds]
    performance = 0.9
    accessibility = 0.95
    best-practices = 0.9
    seo = 0.9
    pwa = 0.8

[[plugins]]
  package = "netlify-plugin-minify-html"
  
  [plugins.inputs]
    contexts = ["production"]

# Environment variables for build
[context.production.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "development"
